// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using petblog.Models;

#nullable disable

namespace PetBlog.Migrations
{
    [DbContext(typeof(MyAppContext))]
    partial class MyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PetBlog.Models.Blog", b =>
                {
                    b.Property<int>("blogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("aktifMi")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("baslik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("guncellemeTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("icerik")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("olusturmaTarihi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("yoneticiId")
                        .HasColumnType("int");

                    b.HasKey("blogId");

                    b.ToTable("Bloglar");
                });

            modelBuilder.Entity("PetBlog.Models.Kayit", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userBilgi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("userFoto")
                        .HasColumnType("longblob");

                    b.HasKey("userID");

                    b.ToTable("kayitli");
                });

            modelBuilder.Entity("PetBlog.Models.Kullanici", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("userID");

                    b.ToTable("kullanicilar");
                });

            modelBuilder.Entity("PetBlog.Models.Pet", b =>
                {
                    b.Property<int>("petID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("petAd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("petBilgi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("petCins")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte[]>("petFoto")
                        .HasColumnType("longblob");

                    b.Property<string>("petTur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("petYas")
                        .HasColumnType("int");

                    b.HasKey("petID");

                    b.ToTable("petler");
                });

            modelBuilder.Entity("PetBlog.Models.Yonetici", b =>
                {
                    b.Property<int>("yoneticiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("eposta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("kullaniciAdi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("yoneticiId");

                    b.ToTable("Yoneticiler");

                    b.HasData(
                        new
                        {
                            yoneticiId = 1,
                            eposta = "admin@admin.com",
                            kullaniciAdi = "admin",
                            sifre = "123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
